### ISSUE TITLE
Feedback on how to make this easiest for people to use

### ISSUE THREAD

**Issue by internettrans** [pcmnac/single-spa-cycle#1]
First off, nice work on this project! Ihave added a link to this repo in [the single-spa docs](https://github.com/CanopyTax/single-spa/blob/master/docs/single-spa-ecosystem.md). You [asked for some feedback](https://twitter.com/pcmnac/status/905791773414391809) on it on Twitter, so here are my thoughts:

1) `@cycle/run` and `@cycle/dom` are [being imported](https://github.com/pcmnac/single-spa-cycle/blob/master/src/single-spa-cycle.js#L1) but they are not listed as dependencies in the package.json. I think the options here are to either put them as peerDependencies (to try to avoid multiple versions of the library being bundled) or to have the libraries passed in as part of the opts. In single-spa-react, single-spa-ember, single-spa-angular2, etc, we do the latter and [have the user provide the libraries as opts](https://github.com/CanopyTax/single-spa-react/blob/master/src/single-spa-react.js#L3-L4). This avoids any oddities with how different package managers handle peerDependencies, and ensures that the user of the single-spa-cycle can use whatever version of CycleJS they want. If you choose to go the peerDependencies route, though, I would recommend doing `{"peerDependencies": "@cycle/run": "*"}` in the package.json so that you aren't specifying any version of cyclejs.

2) If someone uses single-spa-cycle for two cyclejs child applications, there is a bug. The problem is that [there is only one dispose variable](https://github.com/pcmnac/single-spa-cycle/blob/master/src/single-spa-cycle.js#L46) which could be overwritten by multiple child applications. We actually had the same bug in single-spa-react until we fixed it. You can check out the following commits for the issue and how we fixed it: https://github.com/CanopyTax/single-spa-angular1/issues/2 and https://github.com/CanopyTax/single-spa-react/commit/b87521674846cf819199bec0824c9f47b74ba3e6. Basically we ended up putting variables like dispose onto the `opts` object itself. That way if you call singleSpaCycle() more than once, there aren't any variables that collide.

3) It would be slightly nicer to debug if single-spa-cycle created source maps during `npm run build`. All it takes is adding `--source-maps` to [this line](https://github.com/pcmnac/single-spa-cycle/blob/master/package.json#L7). You may have copied that from single-spa-react or one of other single-spa helper libraries, which are also missing the `--source-maps`

Awesome work on this, excited for single-spa to be able to support cyclejs!

**Comment by pcmnac** [comment]
Thanks for feedback, Joel. I've made the changes you suggested. For #1 I actually let to user to pass run() and all drivers (including the DOM). As the html elment is required only by the DOM Driver, I removed the domElementGetter opt.
