### ISSUE TITLE
Github and NPM permissions

### ISSUE THREAD

**Issue by internettrans** [pcmnac/single-spa-cycle#3]
Hey @pcmnac, in order to maintain and support this project for the entire single-spacommunity, could you give me Read/Write access on Github and "owner" permissions on npm?

My github/npm username is joeldenning. To give me npm access, you can run the following command:

```sh
npm owner add joeldenning @pcmnac/single-spa-cycle
```

Thanks!

**Comment by pcmnac** [comment]
Sure @joeldenning. Done!

**Comment by internettrans** [comment]
Thanks!
